### ISSUE TITLE
psg_val.json and psg_tra.json files

### ISSUE THREAD

**Issue by PinkSlime** [franciszzj/VLPrompt#1]
I noticed that while running the code, it requires the psg_val.json and psg_tra.json files. However, I couldn't find these files in the official PSG dataset. Could you please share these two files and briefly explain how they differ from the official configuration JSON files?

**Comment by franciszzj** [comment]
Thank you for your attention. I have just updated the README.
Please download the JSON file you need here: https://github.com/franciszzj/VLPrompt/blob/main/README.md#resource
This file is only different from the official JSON in terms of format. We have revised it according to the format of mmdetection.
