### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 768 but got size 1024 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by hanzefang** [franciszzj/VLPrompt#2]
I am interested in your work.
And I have a question:
The batch size must be 1?
If not, how do I revise the code?

**Comment by franciszzj** [comment]
Thank you for your attention to our work.

The current default config is batch size=1, and we have added a check in the code here: https://github.com/franciszzj/VLPrompt/blob/main/kings_sgg/models/relation_heads/relation_transformer_head_v2.py#L413.
If you wish to use a larger batch size, you can refer to this part: https://github.com/franciszzj/VLPrompt/blob/main/kings_sgg/models/relation_heads/relation_transformer_head_v2.py#L421. However, my experimental experience has shown that using a larger batch size may slightly reduce the performance
