### ISSUE TITLE
About the 3rdpart

### ISSUE THREAD

**Issue by jiuxuanth** [franciszzj/VLPrompt#5]
the code commit the 3rdprat.

- Is this third-party Python library the original code?
- Or has it been partially modified?
- Can I directly install the original library implementation code? 

Looking forward to your reply.

**Comment by franciszzj** [comment]
No modification. Specificly,
- [mmdetection @ e9cae2d](https://github.com/open-mmlab/mmdetection/tree/e9cae2d0787cd5c2fc6165a6061f92fa09e48fb1)
- [transformers @ 546e767](https://github.com/huggingface/transformers/tree/546e7679e7f692ebeefcfc5063cec271a55bae20)
